// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortLinkGenerator.EF.Persistence.Contexts;

namespace ShortLinkGenerator.EF.Persistence.Migrations
{
    [DbContext(typeof(URLContext))]
    [Migration("20201129124318_addModels")]
    partial class addModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShortLinkGenerator.Core.Entities.Url", b =>
                {
                    b.Property<long>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.Property<string>("LinkCode");

                    b.Property<string>("ShortLink")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("UrlId");

                    b.ToTable("Url","URL");
                });

            modelBuilder.Entity("ShortLinkGenerator.Core.Entities.UrlVisitorsCounter", b =>
                {
                    b.Property<long>("CounterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Count");

                    b.Property<DateTime>("LastVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LinkCode");

                    b.HasKey("CounterId");

                    b.ToTable("UrlVisitorsCounters","URL");
                });
#pragma warning restore 612, 618
        }
    }
}
